version: v2

tasks:
  build:
    steps:
    - checkout
    - cache/pull: pip-deps-{{ checksum "requirements.txt" }}
    - commands: 
      - python -c 'import site; print(site.getsitepackages())'
      - pip install -r requirements.txt
    - commands:
      - python test.py
    - cache/push: 
        key: pip-deps-{{ checksum "requirements.txt" }}
        paths:
        - ~/.pyenv/versions/3.7.8/lib/python3.7/site-packages
    - reports/junit: test-reports/*.xml
